name: ci

on:
  pull_request:
    branches:
      - 'main'
jobs:
  ios-test:
    name: iOS Testing
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: example
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Install Pods
        run: cd ios && pod install --repo-update && cd ..

      - name: Add config
        run: echo "${{ secrets.CONFIG_FILE }}" > ./src/config.ts

      - name: Run tests
        run: npm run ios::sim::debug
