export var ActivityType;
(function (ActivityType) {
  ActivityType[(ActivityType['IN_VEHICLE'] = 0)] = 'IN_VEHICLE';
  ActivityType[(ActivityType['BIKING'] = 1)] = 'BIKING';
  ActivityType[(ActivityType['STILL'] = 3)] = 'STILL';
  ActivityType[(ActivityType['UNKNOWN'] = 4)] = 'UNKNOWN';
  ActivityType[(ActivityType['TILTING'] = 5)] = 'TILTING';
  ActivityType[(ActivityType['WALKING'] = 7)] = 'WALKING';
  ActivityType[(ActivityType['RUNNING'] = 8)] = 'RUNNING';
  ActivityType[(ActivityType['AEROBICS'] = 9)] = 'AEROBICS';
  ActivityType[(ActivityType['BADMINTON'] = 10)] = 'BADMINTON';
  ActivityType[(ActivityType['BASEBALL'] = 11)] = 'BASEBALL';
  ActivityType[(ActivityType['BASKETBALL'] = 12)] = 'BASKETBALL';
  ActivityType[(ActivityType['BIATHLON'] = 13)] = 'BIATHLON';
  ActivityType[(ActivityType['HANDBIKING'] = 14)] = 'HANDBIKING';
  ActivityType[(ActivityType['MOUNTAIN_BIKING'] = 15)] = 'MOUNTAIN_BIKING';
  ActivityType[(ActivityType['ROAD_BIKING'] = 16)] = 'ROAD_BIKING';
  ActivityType[(ActivityType['SPINNING'] = 17)] = 'SPINNING';
  ActivityType[(ActivityType['STATIONARY_BIKING'] = 18)] = 'STATIONARY_BIKING';
  ActivityType[(ActivityType['UTILITY_BIKING'] = 19)] = 'UTILITY_BIKING';
  ActivityType[(ActivityType['BOXING'] = 20)] = 'BOXING';
  ActivityType[(ActivityType['CALISTHENICS'] = 21)] = 'CALISTHENICS';
  ActivityType[(ActivityType['CIRCUIT_TRAINING'] = 22)] = 'CIRCUIT_TRAINING';
  ActivityType[(ActivityType['CRICKET'] = 23)] = 'CRICKET';
  ActivityType[(ActivityType['DANCING'] = 24)] = 'DANCING';
  ActivityType[(ActivityType['ELLIPTICAL'] = 25)] = 'ELLIPTICAL';
  ActivityType[(ActivityType['FENCING'] = 26)] = 'FENCING';
  ActivityType[(ActivityType['AMERICAN_FOOTBALL'] = 27)] = 'AMERICAN_FOOTBALL';
  ActivityType[(ActivityType['AUSTRALIAN_FOOTBALL'] = 28)] =
    'AUSTRALIAN_FOOTBALL';
  ActivityType[(ActivityType['ENGLISH_FOOTBALL'] = 29)] = 'ENGLISH_FOOTBALL';
  ActivityType[(ActivityType['FRISBEE'] = 30)] = 'FRISBEE';
  ActivityType[(ActivityType['GARDENING'] = 31)] = 'GARDENING';
  ActivityType[(ActivityType['GOLF'] = 32)] = 'GOLF';
  ActivityType[(ActivityType['GYMNASTICS'] = 33)] = 'GYMNASTICS';
  ActivityType[(ActivityType['HANDBALL'] = 34)] = 'HANDBALL';
  ActivityType[(ActivityType['HIKING'] = 35)] = 'HIKING';
  ActivityType[(ActivityType['HOCKEY'] = 36)] = 'HOCKEY';
  ActivityType[(ActivityType['HORSEBACK_RIDING'] = 37)] = 'HORSEBACK_RIDING';
  ActivityType[(ActivityType['HOUSEWORK'] = 38)] = 'HOUSEWORK';
  ActivityType[(ActivityType['JUMPING_ROPE'] = 39)] = 'JUMPING_ROPE';
  ActivityType[(ActivityType['KAYAKING'] = 40)] = 'KAYAKING';
  ActivityType[(ActivityType['KETTLEBELL_TRAINING'] = 41)] =
    'KETTLEBELL_TRAINING';
  ActivityType[(ActivityType['KICKBOXING'] = 42)] = 'KICKBOXING';
  ActivityType[(ActivityType['KITESURFING'] = 43)] = 'KITESURFING';
  ActivityType[(ActivityType['MARTIAL_ARTS'] = 44)] = 'MARTIAL_ARTS';
  ActivityType[(ActivityType['MEDITATION'] = 45)] = 'MEDITATION';
  ActivityType[(ActivityType['MIXED_MARTIAL_ARTS'] = 46)] =
    'MIXED_MARTIAL_ARTS';
  ActivityType[(ActivityType['P90X_EXERCISES'] = 47)] = 'P90X_EXERCISES';
  ActivityType[(ActivityType['PARAGLIDING'] = 48)] = 'PARAGLIDING';
  ActivityType[(ActivityType['PILATES'] = 49)] = 'PILATES';
  ActivityType[(ActivityType['POLO'] = 50)] = 'POLO';
  ActivityType[(ActivityType['RACQUETBALL'] = 51)] = 'RACQUETBALL';
  ActivityType[(ActivityType['ROCK_CLIMBING'] = 52)] = 'ROCK_CLIMBING';
  ActivityType[(ActivityType['ROWING'] = 53)] = 'ROWING';
  ActivityType[(ActivityType['ROWING_MACHINE'] = 54)] = 'ROWING_MACHINE';
  ActivityType[(ActivityType['RUGBY'] = 55)] = 'RUGBY';
  ActivityType[(ActivityType['JOGGING'] = 56)] = 'JOGGING';
  ActivityType[(ActivityType['RUNNING_ON_SAND'] = 57)] = 'RUNNING_ON_SAND';
  ActivityType[(ActivityType['TREADMILL_RUNNING'] = 58)] = 'TREADMILL_RUNNING';
  ActivityType[(ActivityType['SAILING'] = 59)] = 'SAILING';
  ActivityType[(ActivityType['SCUBA_DIVING'] = 60)] = 'SCUBA_DIVING';
  ActivityType[(ActivityType['SKATEBOARDING'] = 61)] = 'SKATEBOARDING';
  ActivityType[(ActivityType['SKATING'] = 62)] = 'SKATING';
  ActivityType[(ActivityType['CROSS_SKATING'] = 63)] = 'CROSS_SKATING';
  ActivityType[(ActivityType['INDOOR_ROLLERBLADING'] = 64)] =
    'INDOOR_ROLLERBLADING';
  ActivityType[(ActivityType['SKIING'] = 65)] = 'SKIING';
  ActivityType[(ActivityType['BACK_COUNTRY_SKIING'] = 66)] =
    'BACK_COUNTRY_SKIING';
  ActivityType[(ActivityType['CROSS_COUNTRY_SKIING'] = 67)] =
    'CROSS_COUNTRY_SKIING';
  ActivityType[(ActivityType['DOWNHILL_SKIING'] = 68)] = 'DOWNHILL_SKIING';
  ActivityType[(ActivityType['KITE_SKIING'] = 69)] = 'KITE_SKIING';
  ActivityType[(ActivityType['ROLLER_SKIING'] = 70)] = 'ROLLER_SKIING';
  ActivityType[(ActivityType['SLEDDING'] = 71)] = 'SLEDDING';
  ActivityType[(ActivityType['SNOWBOARDING'] = 73)] = 'SNOWBOARDING';
  ActivityType[(ActivityType['SNOWMOBILE'] = 74)] = 'SNOWMOBILE';
  ActivityType[(ActivityType['SNOWSHOEING'] = 75)] = 'SNOWSHOEING';
  ActivityType[(ActivityType['SQUASH'] = 76)] = 'SQUASH';
  ActivityType[(ActivityType['STAIR_CLIMBING'] = 77)] = 'STAIR_CLIMBING';
  ActivityType[(ActivityType['STAIR_CLIMBING_MACHINE'] = 78)] =
    'STAIR_CLIMBING_MACHINE';
  ActivityType[(ActivityType['STAND_UP_PADDLEBOARDING'] = 79)] =
    'STAND_UP_PADDLEBOARDING';
  ActivityType[(ActivityType['STRENGTH_TRAINING'] = 80)] = 'STRENGTH_TRAINING';
  ActivityType[(ActivityType['SURFING'] = 81)] = 'SURFING';
  ActivityType[(ActivityType['SWIMMING'] = 82)] = 'SWIMMING';
  ActivityType[(ActivityType['SWIMMING_SWIMMING_POOL'] = 83)] =
    'SWIMMING_SWIMMING_POOL';
  ActivityType[(ActivityType['SWIMMING_OPEN_WATER'] = 84)] =
    'SWIMMING_OPEN_WATER';
  ActivityType[(ActivityType['TABLE_TENNIS'] = 85)] = 'TABLE_TENNIS';
  ActivityType[(ActivityType['TEAM_SPORTS'] = 86)] = 'TEAM_SPORTS';
  ActivityType[(ActivityType['TENNIS'] = 87)] = 'TENNIS';
  ActivityType[(ActivityType['TREADMILL'] = 88)] = 'TREADMILL';
  ActivityType[(ActivityType['VOLLEYBALL'] = 89)] = 'VOLLEYBALL';
  ActivityType[(ActivityType['VOLLEYBALL_BEACH'] = 90)] = 'VOLLEYBALL_BEACH';
  ActivityType[(ActivityType['VOLLEYBALL_INDOOR'] = 91)] = 'VOLLEYBALL_INDOOR';
  ActivityType[(ActivityType['WAKEBOARDING'] = 92)] = 'WAKEBOARDING';
  ActivityType[(ActivityType['WALKING_FITNESS'] = 93)] = 'WALKING_FITNESS';
  ActivityType[(ActivityType['NORDIC_WALKING'] = 94)] = 'NORDIC_WALKING';
  ActivityType[(ActivityType['WALKING_TREADMILL'] = 95)] = 'WALKING_TREADMILL';
  ActivityType[(ActivityType['WATERPOLO'] = 96)] = 'WATERPOLO';
  ActivityType[(ActivityType['WEIGHTLIFTING'] = 97)] = 'WEIGHTLIFTING';
  ActivityType[(ActivityType['WHEELCHAIR'] = 98)] = 'WHEELCHAIR';
  ActivityType[(ActivityType['WINDSURFING'] = 99)] = 'WINDSURFING';
  ActivityType[(ActivityType['YOGA'] = 100)] = 'YOGA';
  ActivityType[(ActivityType['ZUMBA'] = 101)] = 'ZUMBA';
  ActivityType[(ActivityType['DIVING'] = 102)] = 'DIVING';
  ActivityType[(ActivityType['ERGOMETER'] = 103)] = 'ERGOMETER';
  ActivityType[(ActivityType['ICE_SKATING'] = 104)] = 'ICE_SKATING';
  ActivityType[(ActivityType['INDOOR_SKATING'] = 105)] = 'INDOOR_SKATING';
  ActivityType[(ActivityType['CURLING'] = 106)] = 'CURLING';
  ActivityType[(ActivityType['OTHER'] = 108)] = 'OTHER';
  ActivityType[(ActivityType['CROSSFIT'] = 113)] = 'CROSSFIT';
  ActivityType[(ActivityType['HIIT'] = 114)] = 'HIIT';
  ActivityType[(ActivityType['INTERVAL_TRAINING'] = 115)] = 'INTERVAL_TRAINING';
  ActivityType[(ActivityType['WALKING_STROLLER'] = 116)] = 'WALKING_STROLLER';
  ActivityType[(ActivityType['ELEVATOR'] = 117)] = 'ELEVATOR';
  ActivityType[(ActivityType['ESCALATOR'] = 118)] = 'ESCALATOR';
  ActivityType[(ActivityType['ARCHERY'] = 119)] = 'ARCHERY';
  ActivityType[(ActivityType['SOFTBALL'] = 120)] = 'SOFTBALL';
  ActivityType[(ActivityType['GUIDED_BREATHING'] = 122)] = 'GUIDED_BREATHING';
  ActivityType[(ActivityType['CARDIO_TRAINING'] = 123)] = 'CARDIO_TRAINING';
  ActivityType[(ActivityType['LACROSSE'] = 124)] = 'LACROSSE';
  ActivityType[(ActivityType['STRETCHING'] = 125)] = 'STRETCHING';
  ActivityType[(ActivityType['TRIATHLON'] = 126)] = 'TRIATHLON';
  ActivityType[(ActivityType['INLINE_SKATING'] = 127)] = 'INLINE_SKATING';
  ActivityType[(ActivityType['SKY_DIVING'] = 128)] = 'SKY_DIVING';
  ActivityType[(ActivityType['PADDLING'] = 129)] = 'PADDLING';
  ActivityType[(ActivityType['MOUNTAINEERING'] = 130)] = 'MOUNTAINEERING';
  ActivityType[(ActivityType['FISHING'] = 131)] = 'FISHING';
  ActivityType[(ActivityType['WATER_SKIING'] = 132)] = 'WATER_SKIING';
})(ActivityType || (ActivityType = {}));
