name: ci

on:
  pull_request:
    branches:
      - 'master'
jobs:
  lint-format:
    name: Lint & Format
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install modules
        run: npm install

      - name: Run linter
        run: |
          npm run lint

      - name: Run prettier
        run: |
          npm run format_check

  ios-test:
    # Thanks to https://github.com/edvinasbartkus/react-native-detox-github-actions/blob/master/.github/workflows/ios.yml
    name: iOS Testing
    runs-on: macOS-latest
    needs: lint-format
    defaults:
      run:
        working-directory: example

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Node
        uses: actions/setup-node@v1

      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Rebuild detox
        if: steps.cache.outputs.cache-hit == 'true'
        run: yarn detox clean-framework-cache && yarn detox build-framework-cache

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Cache Pods
        uses: actions/cache@v1
        id: podcache
        with:
          path: ios/Pods
          key: pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Update Pods
        run: |
          gem update cocoapods xcodeproj
          cd ios && pod install && cd ..

      - run: brew tap wix/brew
      - run: brew install applesimutils

      - name: Add config
        run: echo "${{ secrets.CONFIG_FILE }}" > ./src/config.ts

      - run: yarn detox build e2e --configuration ios.sim.debug
      - run: yarn detox test e2e --configuration ios.sim.debug --cleanup --debug-synchronization 200
